const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.MINB_PLAYWRIGHT||'playwright');
const root=process.env.MINB_ROOT||path.join(__dirname,'..');
async function fixture(browser,width=375,mode='recur',opts={}){
 const context=await browser.newContext({viewport:{width,height:900},timezoneId:'Asia/Seoul',serviceWorkers:'block'});
 if(opts.now)await context.clock.setFixedTime(opts.now);
 await context.addInitScript(()=>{
  const auth={onAuthStateChanged(){},getRedirectResult:async()=>null};
  const db={enablePersistence:async()=>{},collection:name=>({doc:id=>({name,id})}),batch:()=>{const writes=[];return{update:(ref,data)=>writes.push({ref,data}),commit:async()=>{if(window.QA.fail)throw Error('test write failure');window.QA.writes.push(writes);}}}};
  window.QA={writes:[],fail:false};window.firebase={initializeApp(){},auth:()=>auth,app:()=>({functions:()=>({httpsCallable:()=>async()=>({data:{holidays:[]}})})}),firestore:Object.assign(()=>db,{FieldValue:{serverTimestamp:()=>1}})};
 });
 await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.hostname!=='minb.test')return route.fulfill({body:'',contentType:'application/javascript'});const file=path.join(root,url.pathname==='/'?'index.html':url.pathname);if(!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/javascript'});});
 const page=await context.newPage();page.setDefaultTimeout(4000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('https://minb.test/'+(opts.page||''));if(opts.page)return{page,context,errors};await page.evaluate(mode=>{
 currentUser={uid:'A',displayName:'테스트'};
 userData={personalRecurring:[],personalDays:{}};
 spaceData={members:['A'],memberProfiles:{A:{name:'테스트'}},days:{},recurring:[]};
 spaceId='space';
 selectedDate=new Date(2026,9,2);
 document.getElementById('loginOverlay').style.display='none';
 if(mode==='recur'||mode==='day')openDayDetail('2026-10-02');
 if(mode==='recur')toggleRecurPanel();
 if(mode==='home')renderAll();
},mode);return{page,context,errors};
}
const cases=[];const test=(name,fn)=>cases.push({name,fn});
test('weekly Friday default is explicit and toggle is accessible',async p=>{await p.evaluate(()=>setRecurMode('weekly'));assert.equal(await p.locator('#recurDayBtns [data-day="5"]').getAttribute('aria-pressed'),'true');assert.match(await p.locator('#recurSummary').textContent(),/매주 금/);});
test('weekday and weekend presets select correct days',async p=>{await p.evaluate(()=>setRecurPreset('weekdays'));assert.deepEqual(await p.evaluate(()=>recurSelDays),[1,2,3,4,5]);await p.evaluate(()=>setRecurPreset('weekends'));assert.deepEqual(await p.evaluate(()=>recurSelDays),[6,0]);assert.match(await p.locator('#recurSummary').textContent(),/매주 토·일/);});
test('range is inclusive and excludes dates before and after',async p=>{assert.deepEqual(await p.evaluate(()=>{userData.personalRecurring=[{id:'x',days:[5],startDate:'2026-10-02',endDate:'2026-10-09'}];return ['2026-09-25','2026-10-02','2026-10-09','2026-10-16'].map(k=>getRecurringFor(new Date(k+'T12:00:00')).length)}),[0,1,1,0]);});
test('legacy rules remain unbounded and month-end behavior survives',async p=>{assert.deepEqual(await p.evaluate(()=>{userData.personalRecurring=[{id:'w',days:[5]},{id:'m',freq:'monthly',monthDay:31},{id:'y',freq:'yearly',month:2,monthDay:29}];return ['2026-01-02','2026-02-28','2028-02-29'].map(k=>getRecurringFor(new Date(k+'T12:00:00')).map(r=>r.id))}),[['w'],['m','y'],['m','y']]);});
test('saving stores selected weekdays and range in private rule',async p=>{await p.locator('#recurInput').fill('금요일 운동');await p.evaluate(()=>setRecurMode('weekly'));await p.locator('#recurEndMode').selectOption('date');await p.locator('#recurEndDate').fill('2026-10-30');await p.evaluate(()=>addRecurring());const r=await p.evaluate(()=>userData.personalRecurring[0]);assert.deepEqual(r.days,[5]);assert.equal(r.startDate,'2026-10-02');assert.equal(r.endDate,'2026-10-30');assert.equal(r.visibility,'private');});
test('invalid end date and empty weekdays prevent persistence',async p=>{await p.locator('#recurInput').fill('잘못된 기간');await p.locator('#recurEndMode').selectOption('date');await p.locator('#recurEndDate').fill('2026-10-01');await p.evaluate(()=>addRecurring());assert.equal(await p.evaluate(()=>QA.writes.length),0);await p.locator('#recurEndMode').selectOption('never');await p.evaluate(()=>{setRecurMode('weekly');toggleRecurDay(5);return addRecurring()});assert.equal(await p.evaluate(()=>QA.writes.length),0);});
test('failed save preserves all input for retry',async p=>{await p.locator('#recurInput').fill('보존할 일정');await p.evaluate(()=>{QA.fail=true;return addRecurring()});assert.equal(await p.locator('#recurInput').inputValue(),'보존할 일정');assert.equal(await p.evaluate(()=>userData.personalRecurring.length),0);});
test('conversion dialog uses source date and identical presets',async p=>{await p.evaluate(()=>{userData.personalDays={'2026-10-02':{todos:[{id:'todo',text:'기존 일정',by:'A'}]}};openRecurSetup('2026-10-02','todo');setRsPreset('weekends')});assert.equal(await p.locator('#rsStartDate').inputValue(),'2026-10-02');await p.locator('#rsEndMode').selectOption('date');await p.locator('#rsEndDate').fill('2026-11-01');await p.evaluate(()=>saveRecurSetup());assert.deepEqual(await p.evaluate(()=>userData.personalRecurring[0].days),[0,6]);assert.equal(await p.evaluate(()=>userData.personalRecurring[0].endDate),'2026-11-01');});
test('shared range stored in shared collection',async p=>{await p.locator('#recurInput').fill('함께 운동');await p.locator('#recurShareInput').check();await p.evaluate(()=>addRecurring());assert.equal(await p.evaluate(()=>spaceData.recurring[0].startDate),'2026-10-02');assert.equal(await p.evaluate(()=>userData.personalRecurring.length),0);});
test('monthly invalid value cannot disagree with summary or persist',async p=>{await p.locator('#recurInput').fill('월간 일정');await p.evaluate(()=>setRecurMode('monthly'));await p.locator('#recurMonthDay').fill('99');await p.locator('#recurMonthDay').dispatchEvent('change');assert.match(await p.locator('#recurSummary').textContent(),/1일부터 31일/);await p.evaluate(()=>addRecurring());assert.equal(await p.evaluate(()=>QA.writes.length),0);});
test('ending disabled clears stale end date from saved rule',async p=>{await p.locator('#recurInput').fill('무기한 일정');await p.locator('#recurEndMode').selectOption('date');await p.locator('#recurEndDate').fill('2026-10-30');await p.locator('#recurEndMode').selectOption('never');await p.evaluate(()=>addRecurring());assert.equal(await p.evaluate(()=>userData.personalRecurring[0].endDate),undefined);});
test('conversion keyboard focus stays in dialog and Escape closes',async p=>{await p.evaluate(()=>{userData.personalDays={'2026-10-02':{todos:[{id:'todo',text:'기존 일정',by:'A'}]}};openRecurSetup('2026-10-02','todo')});const last=p.locator('#recurSetupModal button').last();await last.focus();await p.keyboard.press('Tab');assert.equal(await p.locator('#recurSetupModal button').first().evaluate(el=>el===document.activeElement),true);await p.keyboard.press('Escape');assert.equal(await p.locator('#recurSetupModal').isVisible(),false);});
test('recurring deletion clearly warns entire rule and supports cancel',async p=>{await p.evaluate(()=>{void confirmScheduleDeletion('운동',true)});assert.match(await p.locator('.schedule-confirm-card').textContent(),/반복 일정 전체/);assert.match(await p.locator('.schedule-confirm-card').textContent(),/되돌릴 수 없/);await p.locator('[data-cancel]').click();assert.equal(await p.locator('.schedule-confirm-modal').count(),0);});
module.exports={fixture,chromium};
if(require.main===module)(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const results=[];try{for(const t of cases){const {page,context,errors}=await fixture(b);try{await t.fn(page);assert.deepEqual(errors,[]);results.push({name:t.name,pass:true});}catch(e){results.push({name:t.name,pass:false,error:e.message});}await context.close();}}finally{await b.close()}fs.writeFileSync(process.env.MINB_RESULTS||path.join(require('node:os').tmpdir(),'minb-recurrence-results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));process.exitCode=results.every(x=>x.pass)?0:1;})();
